apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./openstackclient.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/containers/0/image
      value: quay.io/podified-antelope-centos9/openstack-openstackclient:current-podified
  target:
    kind: Pod
