apiVersion: octavia.openstack.org/v1beta1
kind: Octavia
metadata:
  name: octavia
spec:
  databaseInstance: openstack
  databaseAccount: octavia
  serviceUser: octavia
  rabbitMqClusterName: rabbitmq
  secret: osp-secret
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  customServiceConfig: |
    [DEFAULT]
    debug = true
  octaviaHousekeeping:
    databaseInstance: openstack
    databaseAccount: octavia
    serviceUser: octavia
    serviceAccount: octavia
    role: housekeeping
    certssecret: octavia-amp-cert-data
    secret: osp-secret
    preserveJobs: false
    containerImage: quay.io/podified-antelope-centos9/openstack-octavia-housekeeping:current-podified
    customServiceConfig: |
      [DEFAULT]
      debug = true
  octaviaHealthManager:
    databaseInstance: openstack
    databaseAccount: octavia
    serviceUser: octavia
    serviceAccount: octavia
    role: healthmanager
    certssecret: octavia-amp-cert-data
    secret: osp-secret
    preserveJobs: false
    containerImage: quay.io/podified-antelope-centos9/openstack-octavia-health-manager:current-podified
    customServiceConfig: |
      [DEFAULT]
      debug = true
  octaviaWorker:
    databaseInstance: openstack
    databaseAccount: octavia
    serviceUser: octavia
    serviceAccount: octavia
    role: worker
    certssecret: octavia-amp-cert-data
    secret: osp-secret
    preserveJobs: false
    containerImage: quay.io/podified-antelope-centos9/openstack-octavia-worker:current-podified
    customServiceConfig: |
      [DEFAULT]
      debug = true
  octaviaAPI:
    databaseInstance: openstack
    databaseAccount: octavia
    serviceUser: octavia
    serviceAccount: octavia
    secret: osp-secret
    preserveJobs: false
    containerImage: quay.io/podified-antelope-centos9/openstack-octavia-api:current-podified
    customServiceConfig: |
      [DEFAULT]
      debug = true
