apiVersion: octavia.openstack.org/v1beta1
kind: OctaviaHealthManager
metadata:
  name: octavia
spec:
  databaseInstance: openstack
  databaseUser: octavia
  serviceUser: octavia
  containerImage: quay.io/tripleowallabycentos9/openstack-octavia-heatlh-manager:current-tripleo
  replicas: 1
  secret: osp-secret
  # passwordSelectors: TODO
  # nodeSelector: TODO
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  customServiceConfig: |
    [DEFAULT]
    debug = true
  resources:
    requests:
      memory: "500Mi"
      cpu: "1.0"
